### ISSUE TITLE
Feature request; Master-Master replication configuration

### ISSUE THREAD

**Issue by sblommers** [xvik/guice-persist-orient#13]
Hi, maybe some strange request but would it be nice to easily bind multiple servers together to create a master-master or master-slave kinda setup or perhaps post an example on how to do it with guice-persist-orient if it is possible with current codebase?

**Comment by xvik** [comment]
Hi! 
If I understand you correctly, you should setup orient in [distributed mode](http://orientdb.com/docs/2.2/Tutorial-Setup-a-distributed-database.html). On client side, you can try [multi-server configuration](http://orientdb.com/docs/2.2/Distributed-Configuration.html#use-multiple-addresses) or [dns strategy](http://orientdb.com/docs/2.2/Distributed-Configuration.html#use-the-dns), Never tried it but should work.

If you need to have two different connections from the application (e.g. one for write node and another for reads) then you can try to use private modules as [described in guice-persist](https://github.com/google/guice/wiki/GuicePersistMultiModules). This is not an easy way most of the time, but it could work.

I already started working on direct multi-database support, but it's just a prototype now, and unlikely to be released soon (not sure even if it would be successful after all). 
Right now, I want to release 2.2 compatible version and look prototype further only after that.

**Comment by sblommers** [comment]
Hi xvik,
Thank you for your quick reply. I'll investigate more. Your answer is already very helpful !

Thanks for guice-persist-orient!

**Comment by xvik** [comment]
Thank you)
Closing for now, please reopen if there will be other related questions.

**Comment by sblommers** [comment]
For what it's worth, using guice-persist-orient with 2.2.17 and didn't run into anything strange (yet)

**Comment by xvik** [comment]
Yep, it works, except one tiny compatibility problem: `RidUtils.trackIdChange` which is used by `detach` method of base object repository implementation fails due to orient method rename.

There were other things related only to my tests. For example, after switching to 2.2 tests become 3 times slower. Was able to solve this recently by disabling orient security completely in (most) tests.

Also, there are new orient features I want to support directly like sequences, match operator, new eval() etc.
