### ISSUE TITLE
Multi-tenancy support

### ISSUE THREAD

**Issue by rajendrag** [xvik/guice-persist-orient#15]
I really like the comprehensive set of features that covered with this.

I have a multi-tenancy application where I have one database per customer and all the databases will have the same schema. I want to switch the data source based on a ThreadLocal property. Is there a way this project support that? Few hints are good enough. I will take it from there. 

Thank you very much for this awesome repo.

**Comment by sblommers** [comment]
You can use private modules, named bindings and expose only those named repositories (if you use those). In your application you could use the injector to fetch the exposed repository using those named binding.
I use a private module for every database together with owner to keep configurations clean.

**Comment by rajendrag** [comment]
In my case, the tenants can be created dynamically, not sure, if I can install a PrivateModule in runtime (I don't have much experience with Guice yet). 

Also, as my schema is same across the databases, having whole new OrientModule for every database seems to be heavy, am I correct? What I was looking for is to switch the data source of the connection based on the TenantId which is available in ThreadLocal.

Am I thinking in a wrong direction? that's not how this works?

**Comment by sblommers** [comment]
You can create PrivateModules and install them on runtime, just create your own module class that extends PrivateModule and use a name in your constructor, that way you can just install as many as you like to split everyting apart using that name for your bindings. Currently creating a new database requires OrientModule which is indeed heavy in usage, it initializes/creates/restores the database but this is needed, but it is only very heavy when installing the module. I have a server having 30 split OrientModules in 1 Jetty container, works perfectly and resource load is pretty normal, it does need a big amount of memory depending on your amount of data and load on your production system so don't save on memory in this server. In my case every OrientModule has it's own schema but names can collide, i prevent that by always having a new database. My classes are sometimes generated and I have no control on class-names.

Maybe the best scalable solution for you is to just add tentant info to your schema, that way you would have still 1 database. But I guess you already tought of that. OrientDB is pretty powerful and can handle a lot of data. Also this project can help you with scalability/pagination problems. Sharding your data later on when needed to create another database for a larger(specific, higher paying) tentant will be easy.

Maybe @xvik has some good points on this?

Good luck!

**Comment by xvik** [comment]
If you are ready to get your hands dirty, then there is a way, but first I would like to pay attention to @sblommers suggestion about the single database: you can create database users dynamically and use orient permissions to limit access ([do you know that you can control access on record level?](http://orientdb.com/docs/last/Database-Security.html#record-level-security)). Switching context user is [already supported](https://github.com/xvik/guice-persist-orient/blob/master/src/main/java/ru/vyarus/guice/persist/orient/db/PersistentContext.java#L175).

**Dynamic solution:**

There is a [pools concept](https://github.com/xvik/guice-persist-orient/wiki/Pools): an abstraction between the library and orient pools.

There are 3 pools by default: for the document, object and graph connections (the last two types are initialized only when object and graph jars are available in the classpath). Document pool is the major one. It actually creates orient pool to manage document connections. Other pools (object and graph) use document pool to acquire the connection and then to return specific api objects (created with acquired document connection). This way transaction is unified between all connection types.

You can implement your own pool with tenants support: implement  [pools interface](https://github.com/xvik/guice-persist-orient/blob/master/src/main/java/ru/vyarus/guice/persist/orient/db/pool/PoolManager.java). Look [document pool](https://github.com/xvik/guice-persist-orient/blob/master/src/main/java/ru/vyarus/guice/persist/orient/db/pool/DocumentPool.java) implementation as an example. Pay attention that pool must properly support transactions (don't provide new connections for the ongoing transaction). There is a mention in javadoc about mandatory UserManager usage, but if you don't use [dynamic user switching](https://github.com/xvik/guice-persist-orient/blob/master/src/main/java/ru/vyarus/guice/persist/orient/db/user/UserManager.java#L82), you can avoid that (most likely, all databases will have different credentials and the idea of user manager become useless).

Pay attention, that one connection is always acquired from the pool during startup (for possible initialization). So your pool must provide something even without context user.

To register your pool: extend OrientModule and override [configurePools](https://github.com/xvik/guice-persist-orient/blob/master/src/main/java/ru/vyarus/guice/persist/orient/OrientModule.java#L173) method.

If you need object/graph connections most likely you will be able to use provided pools (because they use document pool for connection as described above).

Normally, schema initialization is called [just after pools startup](https://github.com/xvik/guice-persist-orient/blob/master/src/main/java/ru/vyarus/guice/persist/orient/db/DatabaseManager.java#L94). So in your case, only initial database will be initialized (the one that was obtained during startup). So if you need to reuse schema initialization for all other (dynamic) databases, you will need to do it manually inside your pool. But, it's just a one line call.

Ask me if you will have problems doing this. 
And please tell me about your results: it's a very interesting use-case.

**Comment by rajendrag** [comment]
Thank you very much, both of you. This is indeed helpful and insightful. 

I have considered the single database option, but we have explicit agreements with our customers saying that their data is not merged with any other customer. I was thinking about having my own pool and "get()" will return me the tenant specific connection. Your reply is very helpful and exactly points to "where to start". 

I will work on it and let you guys know how it goes. Probably I will create a sample project on Github.

Thank you very much again.
