### ISSUE TITLE
setNullValuesIgnored seems to always be false when using @Index(value=INDEX_TYPE.NOTUNIQUE

### ISSUE THREAD

**Issue by sblommers** [xvik/guice-persist-orient#16]
Hi there!
I'm using version 3.3.0. Using the following index annotation
@Index(value=INDEX_TYPE.NOTUNIQUE)
which defaults to ignoreNullValues=true will always force a rebuilt of the index when restarting.
When specifically setting @Index(value=INDEX_TYPE.NOTUNIQUE, ignoreNullValues=false) it will not rebuild after every restart.
Perhaps this is a bug in OrientDB but I came across a few issues about this and I don't really know where to look.

See https://github.com/orientechnologies/orientdb/issues/6746 (closed but not really fixed?)
Or might this be a bug in the IndexFieldExtension not picking up from OrientDB

Please close this if it is not a guice-persist-orient bug.

Thanks for this wonderful library!

**Comment by sblommers** [comment]
Thanks for fixing this!

**Comment by xvik** [comment]
Hi!
Sorry for the long response - I was obsessed by finishing python plugin before NY (will need it for a new documentation site instead of wiki). 

I was not able to reproduce your issue, but obviously updating index definition is not recommended practice (thank you for the link!). So I rewrite index creation in the way as it's [described in docs](http://orientdb.com/docs/last/Indexes.html#indexes-and-null-values).

After the fix tests show one side effect (which indirectly confirms issue): ignoreNullValues=trues composite indexes are not used for queries by just one field ([without flag](https://github.com/xvik/guice-persist-orient/commit/eadc8596623b90af270a4a7647f77fd5401907f7#diff-4790508869311fde7a9e60e6d69d5df4R47), [with flag](https://github.com/xvik/guice-persist-orient/commit/eadc8596623b90af270a4a7647f77fd5401907f7#diff-4790508869311fde7a9e60e6d69d5df4R64)). This makes this fix a breaking change (cause side effects): since orient 2.2 ignoreNullValues is false by default, so default value in annotation contradict it.

I will also update orient to the latest (2.2.31), which require some deprecated apis cleanups and after that release 3.3.1 (hope to do it soon).
