### ISSUE TITLE
@Var using a list of type <String> and IN does not work

### ISSUE THREAD

**Issue by sblommers** [xvik/guice-persist-orient#18]
Hi there,

I am using the following query:
```java
@Query("update Required set done = false where requiredId IN $rids")
void undo(@Var("rids") List<String> rids);
```

This works if rids is of type `List<Long>` because it results in [232,2232]
But in case this is a `List<String>` I would expect ["232Ad8d","sadA34d"] but it results in [232Ad8d,sadA34d] when the query get's executed. 

Am I doing something wrong? Is there an easy way to log queries?

**Comment by xvik** [comment]
Hi!

`@Var` extension actually use orient native variables (`com.orientechnologies.orient.core.command.OCommandContext#setVariable`) so the list in your example is directly set into query object and further handling is pure orient logic. And that's why logging will not help (but it's a good idea to add some logs for the future!).

I'm not sure but in your case should help [`@RidElVar`](https://github.com/xvik/guice-persist-orient/wiki/Repository-command-methods#ridelvar). It works like ElVar - will convert list and embed it inside the query. Should be the best solution for rids. If I remember correctly, I did rid vars exactly for the same case.

I doubt, but direct parameter binding could work too

```java
@Query("update Required set done = false where requiredId IN ?")
void undo(List<String> rids);
```

.. or will not work.. it depends on orient version.

**Comment by xvik** [comment]
Aaah I didn't note that its update query :) 

Yes, query and command executions are different (not logical, but fact), so it's "normal" that vars not work properly. 

Have you tried simple parameter binding (last example in my comment)? It should work in this case.
If not then I could suggest only to manually convert list into string (["dfdf","fdfd"]) and use elvar to embed it into command or try to use [script](https://github.com/xvik/guice-persist-orient/wiki/Repository-command-methods#script).. not sure but it *could* work.. ([examples from test](https://github.com/xvik/guice-persist-orient/blob/master/src/test/groovy/ru/vyarus/guice/persist/orient/repository/command/script/ScriptCases.groovy#L23).. it's again simple posiotional argument, but could work properly in script)

**Comment by sblommers** [comment]
I tried simple parameter binding and it works! Yay! Thanks for your help!
