### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by davidsowerby** [xvik/guice-persist-orient#2]
Hi, your project looks interesting, but could you tell me if it supports multiple instances of OrientDb?  From your README it looks as though it is built on guice-persist, which supports only one instance.  (I prefer to use Onami persist for that reason)

**Comment by xvik** [comment]
guice-persist docs suggest using private modules for multiple db support (https://github.com/google/guice/wiki/GuicePersistMultiModules).
The main idea is that each database logic is encapsulated in private module and specific db services are exported with annotation or named marker.
I'm sure onami uses similar approach internally (at least it looks like from their example ). 
I will try to add builder like this too to easily support multiple db.

**Comment by davidsowerby** [comment]
Thanks for the quick reply - that would be good to see, the requirement for multiple db is much more common than it used to be, and with the multi-model OrientDb possibly even more common.  I will add this to [my project](https://github.com/davidsowerby/krail), so thank you for making this code available - I have a very (very!) simple OrientDb integration, but yours is far more complete.

One other suggestion might be support for key-value;  I note from the OrientDb documentation that they use an index for a fast key-value solution;  added to the document, graph and object APIs, it makes an extremely flexible database.

**Comment by xvik** [comment]
I was thinking about multiple db support, because i have such case with orient db before i wrote this lib. It was few years ago and I was using private modules, but integration was much much simplier (lib evolve from that small part). 
Now I see some potential problems with current lib usage with private modules and it may not be so simple as before, but will try to solve it. And it would be great if it will cover your needs :)

Not sure that orient multi-model nature will drive multiple db requirement because it could use the same db in any way. My case was very specific, but anyway this is a good option to have.

Regarding key-value, I have custom annotation to create index from pojo during scheme mapping (https://github.com/xvik/guice-persist-orient/wiki/Object-scheme-initializer#compositeindex). Indexes could be queried with usual queries mechanism (http://www.orientechnologies.com/docs/last/Indexes.html#lookup) and I have support for queries through repositories. So indexes should be already well covered. 
Did i miss something? Im open for suggestions.

**Comment by davidsowerby** [comment]
> Not sure that orient multi-model nature will drive multiple db requirement because it could use the same db in any way. My case was very specific, but anyway this is a good option to have.

Since we are both agreed that multiple db support is a good idea, it does not really matter why we think that -  but where I see OrientDb promoting multiple dbs is in an environment where logical separation of databases has some architectural benefit, but OrientDb is able to fill several roles.

> Regarding key-value, I have custom annotation to create index

Thanks, I did not see that when I was thinking about key-value, but yes, it looks like it would support that.  

It will take me a little time to understand everything you have here, but it does look comprehensive, so thank you again.
