### ISSUE TITLE
Feature: Move @Generic into Guice-Ext-Annotations OR Generics-Resolver

### ISSUE THREAD

**Issue by nkoterba** [xvik/guice-persist-orient#8]
Hello -

First, great project!  Using extensively.  In some of my other stuff the `@Generic("T")` annotation would be super useful.  As that is not explicitly **orient** related, do you have any plans to expose that in its own project or one of your other Github projects?

Thanks!

**Comment by xvik** [comment]
Hello,

Thank you :)
`@Generic` annotation is a part of repository delegate method extension. 
It works only because original method call is delegated to some other method, so I could add other parameters. In case of direct method call you cant add new parameters only replace some existing, but it will look ugly.

I always try to generalize features, but here I have no idea how it could be done and when something like this could be useful. If you have real use case I would love to hear it.

If you simply need generic its just one line with generics-resolver:
```java
GenericsResolver.resolve(MyRootClass.class).type(MyClass.class).generic("T");
```
where `MyRootClass extends MyClass<Something>`

**Comment by nkoterba** [comment]
@xvik I see your point.

I've now spent a day looking through guice-persist-orient and see how you're using Guice AOP in various parts of the application.

Going to close this "feature".
